{
  'getUserProfiles': {
    query: 'SELECT u.id AS user_id, u.username, p.id AS profile_id, p.name AS profile_name FROM public."user" u JOIN public."user_profile" up ON u.id = up.id_user JOIN public."profile" p ON up.id_profile = p.id WHERE u.username = $1;',
      structure_params: { username: 'string' },
      orderArray: ['username']
  },
  'getUsersProfiles': {
    query: 'SELECT u.id AS user_id, u.username, p.id AS profile_id, p.name AS profile_name FROM public."user" u JOIN public."user_profile" up ON u.id = up.id_user JOIN public."profile" p ON up.id_profile = p.id',
      structure_params: { },
      orderArray: []
  },
  'delUserProfile': {
    query: 'DELETE FROM public."user_profile" WHERE id_user = (SELECT id FROM public."user" WHERE username = $1) AND id_profile = (SELECT id FROM public."profile" WHERE name = $2);',
      structure_params: { username: 'string', profile_name: 'string' },
      orderArray: ['username', 'profile_name']
  },
  'getProfileOptions': {
    query: 'SELECT p.id AS profile_id, p.name AS profile_name, o.id AS option_id, o.name AS option_name FROM public."profile" p JOIN public."option_profile" op ON p.id = op.id_profile JOIN public."option" o ON op.id_option = o.id WHERE p.name = $1;',
      structure_params: { profile_name: 'string' },
      orderArray: ['profile_name']
  },
  'getProfilesOptions': {
    query: 'SELECT p.id AS profile_id, p.name AS profile_name, o.id AS option_id, o.name AS option_name FROM public."profile" p JOIN public."option_profile" op ON p.id = op.id_profile JOIN public."option" o ON op.id_option = o.id',
    structure_params: { },
    orderArray: []
  },
  'delProfileOption': {
    query: 'DELETE FROM public."option_profile" WHERE id_option = (SELECT id FROM public."option" WHERE name = $1) AND id_profile = (SELECT id FROM public."profile" WHERE name = $2);',
      structure_params: { option_name: 'string', profile_name: 'string' },
      orderArray: ['option_name', 'profile_name']
  },
  'getMenuOptions': {
    query: 'SELECT m.id AS menu_id, m.name AS menu_name, o.id AS option_id, o.name AS option_name FROM public."menu" m JOIN public."option_menu" om ON m.id = om.id_menu JOIN public."option" o ON om.id_option = o.id WHERE m.name = $1;',
      structure_params: { menu_name: 'string' },
      orderArray: ['menu_name']
  },
  'getMenusOptions': {
    query: 'SELECT m.id AS menu_id, m.name AS menu_name, o.id AS option_id, o.name AS option_name FROM public."menu" m JOIN public."option_menu" om ON m.id = om.id_menu JOIN public."option" o ON om.id_option = o.id',
    structure_params: { },
    orderArray: []
  },
  'delMenuOption': {
    query: 'DELETE FROM public."option_menu" WHERE id_option = (SELECT id FROM public."option" WHERE name = $1) AND id_menu = (SELECT id FROM public."menu" WHERE name = $2);',
      structure_params: { option_name: 'string', menu_name: 'string' },
      orderArray: ['option_name', 'menu_name']
  },
  'getMenuOptionsProfile': {
    query: 'SELECT m.id_parent, m.id AS menu_id, m.name AS menu_name, o.tx, o.id AS option_id, o.name AS option_name, p.id AS profile_id, p.name AS profile_name FROM public."menu" m JOIN public."option_menu" om ON m.id = om.id_menu JOIN public."option" o ON om.id_option = o.id JOIN public."option_profile" op ON o.id = op.id_option JOIN public."profile" p ON op.id_profile = p.id WHERE m.name = $1 AND p.name = $2;',
      structure_params: { menu_name: 'string', profile_name: 'string' },
      orderArray: ['menu_name', 'profile_name']
  },
  'getMenusOptionsProfile': {
    query: 'SELECT m.id_parent, m.id AS menu_id, m.name AS menu_name, o.tx, o.id AS option_id, o.name AS option_name, o.description, p.id AS profile_id, p.name AS profile_name FROM public."menu" m JOIN public."option_menu" om ON m.id = om.id_menu JOIN public."option" o ON om.id_option = o.id JOIN public."option_profile" op ON o.id = op.id_option JOIN public."profile" p ON op.id_profile = p.id WHERE p.name = $1;',
      structure_params: { profile_name: 'string' },
      orderArray: ['profile_name']
  },
  'getMenusOptionsProfiles': {
    query: 'SELECT m.id_parent, m.id AS menu_id, m.name AS menu_name, o.tx, o.id AS option_id, o.name AS option_name, o.description, p.id AS profile_id, p.name AS profile_name FROM public."menu" m JOIN public."option_menu" om ON m.id = om.id_menu JOIN public."option" o ON om.id_option = o.id JOIN public."option_profile" op ON o.id = op.id_option JOIN public."profile" p ON op.id_profile = p.id',
    structure_params: { },
    orderArray: []
  },
  'getProfileMethods': {
    query: 'SELECT p.id AS profile_id, p.name AS profile_name, m.id AS method_id, m.name AS method_name FROM public."profile" p JOIN public."method_profile" mp ON p.id = mp.id_profile JOIN public."method" m ON mp.id_method = m.id WHERE p.name = $1;',
      structure_params: { profile_name: 'string' },
      orderArray: ['profile_name']
  },
  'getProfilesMethods': {
    query: 'SELECT p.id AS profile_id, p.name AS profile_name, m.id AS method_id, m.name AS method_name FROM public."profile" p JOIN public."method_profile" mp ON p.id = mp.id_profile JOIN public."method" m ON mp.id_method = m.id',
    structure_params: { },
    orderArray: []
  },
  'delProfileMethod': {
    query: 'DELETE FROM public."method_profile" WHERE id_method = (SELECT id FROM public."method" WHERE name = $1) AND id_profile = (SELECT id FROM public."profile" WHERE name = $2);',
      structure_params: { method_name: 'string', profile_name: 'string' },
      orderArray: ['method_name', 'profile_name']
  },
  'getClassMethods': {
    query: 'SELECT c.id AS class_id, c.name AS class_name, m.id AS method_id, m.name AS method_name FROM public."class" c JOIN public."class_method" cm ON c.id = cm.id_class JOIN public."method" m ON cm.id_method = m.id WHERE c.name = $1;',
      structure_params: { class_name: 'string' },
      orderArray: ['class_name']
  },
  'getClassesMethods': {
    query: 'SELECT c.id AS class_id, c.name AS class_name, m.id AS method_id, m.name AS method_name FROM public."class" c JOIN public."class_method" cm ON c.id = cm.id_class JOIN public."method" m ON cm.id_method = m.id',
    structure_params: { },
    orderArray: []
  },
  'delClassMethod': {
    query: 'DELETE FROM public."class_method" WHERE id_class = (SELECT id FROM public."class" WHERE name = $1) AND id_method = (SELECT id FROM public."method" WHERE name = $2);',
      structure_params: { class_name: 'string', method_name: 'string' },
      orderArray: ['class_name', 'method_name']
  },
  'getSubsystemClassesMethods': {
    query: 'SELECT s.id AS subsystem_id, s.name AS subsystem_name, c.id AS class_id, c.name AS class_name, m.id AS method_id, m.name AS method_name FROM public."subsystem" s JOIN public."subsystem_class" sc ON s.id = sc.id_subsystem JOIN public."class" c ON sc.id_class = c.id JOIN public."class_method" cm ON c.id = cm.id_class JOIN public."method" m ON cm.id_method = m.id WHERE s.name = $1;',
      structure_params: { subsystem_name: 'string' },
      orderArray: ['subsystem_name']
  },
  'registerUser': {
    query: 'INSERT INTO public."user" (user_na, user_pw, person_id) VALUES ($1, $2, $3) RETURNING user_id AS id, user_na AS username, person_id;'
    ,structure_params: { username: 'string', password: 'string', person_id: 'int' }
    ,orderArray: ['username', 'password', 'person_id']
  }
  ,
  'getUserById': {
    query: 'SELECT u.user_id AS id, u.user_na AS username, p.person_em AS email, p.person_na AS name FROM public."user" u LEFT JOIN public.person p ON u.person_id = p.person_id WHERE u.user_id = $1;'
    ,structure_params: { id: 'int' }
    ,orderArray: ['id']
  }
  ,
  'updateUserPasswordByUsername': {
    query: 'UPDATE public."user" SET user_pw = $1 WHERE user_na = $2 RETURNING user_id AS id, user_na AS username;'
    ,structure_params: { password: 'string', username: 'string' }
    ,orderArray: ['password', 'username']
  }
  ,
  'countUserByEmail': {
    query: 'SELECT COUNT(*) AS count FROM public.person WHERE person_em = $1;'
    ,structure_params: { email: 'string' }
    ,orderArray: ['email']
  }
  ,
  'countUserByUsername': {
    query: 'SELECT COUNT(*) AS count FROM public."user" WHERE user_na = $1;'
    ,structure_params: { username: 'string' }
    ,orderArray: ['username']
  }
  ,
  'getUser': {
    query: 'SELECT u.user_id AS id, u.user_na AS username, u.user_pw AS password, p.person_em AS email, p.person_na AS name, p.person_ln AS lastname, p.person_ci AS ci FROM public."user" u LEFT JOIN public.person p ON u.person_id = p.person_id WHERE u.user_na = $1',
    structure_params: { username: 'string' },
    orderArray: ['username']
  },
  'getUserByEmail': {
    query: 'SELECT u.user_id AS id, u.user_na AS username, u.user_pw AS password, p.person_em AS email, p.person_na AS name, p.person_ln AS lastname, p.person_ci AS ci FROM public."user" u JOIN public.person p ON u.person_id = p.person_id WHERE p.person_em = $1;',
    structure_params: { email: 'string' },
    orderArray: ['email']
  },
  'updateUserPassword': {
    query: 'UPDATE public."user" SET user_pw = $1 WHERE user_id = $2 RETURNING user_id AS id, user_na AS username;',
    structure_params: { password: 'string', userId: 'int' },
    orderArray: ['password', 'userId']
  },
  'insertPerson': {
    query: 'INSERT INTO public.person (person_ci, person_na, person_ln, person_em, person_ph) VALUES ($1, $2, $3, $4, $5) RETURNING person_id;',
    structure_params: { ci: 'string', name: 'string', lastname: 'string', email: 'string', phone: 'string' },
    orderArray: ['ci', 'name', 'lastname', 'email', 'phone']
  },
  'insertUserProfile': {
    query: 'INSERT INTO public.user_profile (user_id, profile_id) VALUES ($1, $2) RETURNING user_profile_id;'
    ,structure_params: { user_id: 'int', profile_id: 'int' }
    ,orderArray: ['user_id', 'profile_id']
  },
  'getProfileByName': {
    query: 'SELECT profile_id, profile_de FROM public.profile WHERE profile_de = $1;'
    ,structure_params: { profile_name: 'string' }
    ,orderArray: ['profile_name']
  }
  ,
  'insertProfile': {
    query: 'INSERT INTO public.profile (profile_de) VALUES ($1) RETURNING profile_id, profile_de;',
    structure_params: { profile_name: 'string' },
    orderArray: ['profile_name']
  }
}
