services:
  postgres:
    image: postgres:16
    container_name: uni_postgres
    restart: unless-stopped
    env_file: ../env/docker.env
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5

  backups:
    image: prodrigestivill/postgres-backup-local:latest
    container_name: uni_pg_backups
    restart: unless-stopped
    env_file: ../env/docker.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_DB: 'postgres'
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'

      BACKUP_ON_START: 'TRUE'

      BACKUP_KEEP_DAYS: 7
      SCHEDULE: '@daily'
      HEALTHCHECK_PORT: 8080
    volumes:
      - ./backups:/backups
    depends_on:
      - postgres
