services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16}
    container_name: ${POSTGRES_CONTAINER_NAME:-uni_postgres}
    restart: unless-stopped
    env_file: ../env/${APP_ENV:-development}/docker.env
    ports:
      - '${POSTGRES_BIND_IP:-127.0.0.1}:${POSTGRES_BIND_PORT:-5432}:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5

  backups:
    image: ${BACKUP_IMAGE:-prodrigestivill/postgres-backup-local:16}
    container_name: ${BACKUP_CONTAINER_NAME:-uni_pg_backups}
    restart: unless-stopped
    env_file: ../env/${APP_ENV:-development}/docker.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_DB: 'postgres'
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
    volumes:
      - ./backups:/backups
    depends_on:
      - postgres
