-- ============================================================
-- schema.sql
-- Proyecto: Web II | Motor: PostgreSQL
-- ============================================================
-- Convencion:
--   1) SEGURIDAD / IDENTIDAD  -> no alterar estructura (framework)
--   2) NEGOCIO                -> inventario + prestamos (lenguaje de dominio)
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Dominios reutilizables
-- ------------------------------------------------------------
CREATE DOMAIN email_address AS VARCHAR(150)
    CHECK (VALUE ~* '^[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}$');

CREATE DOMAIN document_identifier AS VARCHAR(30)
    CHECK (VALUE ~ '^[A-Za-z0-9\-]{5,30}$');

CREATE DOMAIN phone_number AS VARCHAR(30)
    CHECK (VALUE ~ '^\+?[0-9 ()\-]{7,20}$');

-- ============================================================
-- 1) SEGURIDAD E IDENTIDAD (estructura del framework)
-- ============================================================

CREATE TABLE IF NOT EXISTS group_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_group_type_name UNIQUE (name),
    CONSTRAINT ck_group_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id document_identifier NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone phone_number,
    degree VARCHAR(150),
    address TEXT,
    birth_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_person_first_name_not_blank CHECK (btrim(first_name) <> ''),
    CONSTRAINT ck_person_last_name_not_blank CHECK (btrim(last_name) <> '')
);

CREATE TABLE IF NOT EXISTS person_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id) ON DELETE RESTRICT,
    group_id BIGINT NOT NULL REFERENCES group_type(id) ON DELETE RESTRICT,
    CONSTRAINT uq_person_group_person_group UNIQUE (person_id, group_id)
);

CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    email email_address,
    password_hash TEXT NOT NULL,
    is_solvency BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    person_id BIGINT REFERENCES person(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_user_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_user_password_hash_not_blank CHECK (btrim(password_hash) <> '')
);

CREATE TABLE IF NOT EXISTS profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_profile_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    profile_id BIGINT NOT NULL REFERENCES profile(id) ON DELETE RESTRICT,
    CONSTRAINT uq_user_profile UNIQUE (user_id, profile_id)
);

CREATE TABLE IF NOT EXISTS "option" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_option_name UNIQUE (name),
    CONSTRAINT ck_option_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS option_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profile(id) ON DELETE RESTRICT,
    option_id BIGINT NOT NULL REFERENCES "option"(id) ON DELETE RESTRICT,
    CONSTRAINT uq_option_profile UNIQUE (profile_id, option_id)
);

CREATE TABLE IF NOT EXISTS subsystem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_subsystem_name UNIQUE (name),
    CONSTRAINT ck_subsystem_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    subsystem_id BIGINT NOT NULL REFERENCES subsystem(id) ON DELETE RESTRICT,
    CONSTRAINT uq_menu_name_subsystem UNIQUE (name, subsystem_id),
    CONSTRAINT ck_menu_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS option_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id BIGINT NOT NULL REFERENCES "option"(id) ON DELETE RESTRICT,
    menu_id BIGINT NOT NULL REFERENCES menu(id) ON DELETE RESTRICT,
    CONSTRAINT uq_option_menu UNIQUE (option_id, menu_id)
);

CREATE TABLE IF NOT EXISTS "class" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_class_name UNIQUE (name),
    CONSTRAINT ck_class_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS subsystem_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subsystem_id BIGINT NOT NULL REFERENCES subsystem(id) ON DELETE RESTRICT,
    class_id BIGINT NOT NULL REFERENCES "class"(id) ON DELETE RESTRICT,
    CONSTRAINT uq_subsystem_class UNIQUE (subsystem_id, class_id)
);

CREATE TABLE IF NOT EXISTS "method" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_method_name UNIQUE (name),
    CONSTRAINT ck_method_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS class_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL REFERENCES "class"(id) ON DELETE RESTRICT,
    method_id BIGINT NOT NULL REFERENCES "method"(id) ON DELETE RESTRICT,
    CONSTRAINT uq_class_method UNIQUE (class_id, method_id)
);

CREATE TABLE IF NOT EXISTS method_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_id BIGINT NOT NULL REFERENCES "method"(id) ON DELETE RESTRICT,
    profile_id BIGINT NOT NULL REFERENCES profile(id) ON DELETE RESTRICT,
    CONSTRAINT uq_method_profile UNIQUE (method_id, profile_id)
);

CREATE TABLE IF NOT EXISTS "transaction" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subsystem_id BIGINT NOT NULL REFERENCES subsystem(id) ON DELETE RESTRICT,
    class_id BIGINT NOT NULL REFERENCES "class"(id) ON DELETE RESTRICT,
    method_id BIGINT NOT NULL REFERENCES "method"(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_transaction_scope UNIQUE (subsystem_id, class_id, method_id)
);

CREATE TABLE IF NOT EXISTS audit_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_audit_type_name UNIQUE (name),
    CONSTRAINT ck_audit_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(100) NOT NULL,
    method VARCHAR(50) NOT NULL,
    event_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    details TEXT,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    type_id BIGINT NOT NULL REFERENCES audit_type(id) ON DELETE RESTRICT,
    CONSTRAINT ck_audit_entity_name_not_blank CHECK (btrim(entity_name) <> ''),
    CONSTRAINT ck_audit_method_not_blank CHECK (btrim(method) <> '')
);

CREATE TABLE IF NOT EXISTS notification_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_notification_type_name UNIQUE (name),
    CONSTRAINT ck_notification_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    sent_at TIMESTAMPTZ,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    type_id BIGINT NOT NULL REFERENCES notification_type(id) ON DELETE RESTRICT,
    CONSTRAINT ck_notification_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT ck_notification_message_not_blank CHECK (btrim(message) <> '')
);

-- ============================================================
-- 2) NEGOCIO: CATALOGO E INVENTARIO
--    Vocabulario alineado a la UI: equipos / componentes
-- ============================================================

-- equipo | componente
CREATE TABLE IF NOT EXISTS item_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_consumable BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_item_category_name UNIQUE (name),
    CONSTRAINT ck_item_category_name_not_blank CHECK (btrim(name) <> '')
);

-- Condicion fisica (Bueno, Danado, Nuevo, Usado)
CREATE TABLE IF NOT EXISTS item_condition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_item_condition_name UNIQUE (name),
    CONSTRAINT ck_item_condition_name_not_blank CHECK (btrim(name) <> '')
);

-- Estatus operativo (Disponible, Mantenimiento, Ocupado, Stock, Asignado, Agotado)
CREATE TABLE IF NOT EXISTS item_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_item_status_name UNIQUE (name),
    CONSTRAINT ck_item_status_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    parent_id BIGINT REFERENCES location(id) ON DELETE SET NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_location_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    brand VARCHAR(100),
    model VARCHAR(100),
    category_id BIGINT NOT NULL REFERENCES item_category(id) ON DELETE RESTRICT,
    condition_id BIGINT REFERENCES item_condition(id) ON DELETE SET NULL,
    status_id BIGINT REFERENCES item_status(id) ON DELETE SET NULL,
    is_consumable BOOLEAN NOT NULL DEFAULT FALSE,
    cost NUMERIC(12,2) NOT NULL DEFAULT 0,
    acquisition_date DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_item_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_item_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_item_cost_non_negative CHECK (cost >= 0)
);

-- Stock por ubicacion (antes: inventory)
CREATE TABLE IF NOT EXISTS stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES item(id) ON DELETE RESTRICT,
    location_id BIGINT NOT NULL REFERENCES location(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_stock_item_location UNIQUE (item_id, location_id),
    CONSTRAINT ck_stock_quantity_non_negative CHECK (quantity >= 0)
);

-- ============================================================
-- 3) NEGOCIO: PRESTAMOS Y DEVOLUCIONES
-- ============================================================

CREATE TABLE IF NOT EXISTS loan_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_loan_status_name UNIQUE (name),
    CONSTRAINT ck_loan_status_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS loan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    processed_by_user_id BIGINT REFERENCES "user"(id) ON DELETE RESTRICT,
    status_id BIGINT NOT NULL REFERENCES loan_status(id) ON DELETE RESTRICT,
    booked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    due_at TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    observations TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_loan_due_after_booked CHECK (due_at >= booked_at),
    CONSTRAINT ck_loan_returned_after_booked CHECK (
        returned_at IS NULL OR returned_at >= booked_at
    )
);

CREATE TABLE IF NOT EXISTS loan_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL REFERENCES loan(id) ON DELETE RESTRICT,
    stock_id BIGINT NOT NULL REFERENCES stock(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL DEFAULT 1,
    returned_quantity INTEGER NOT NULL DEFAULT 0,
    fine NUMERIC(12,2) NOT NULL DEFAULT 0,
    return_condition_id BIGINT REFERENCES item_condition(id) ON DELETE SET NULL,
    observations TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_loan_item_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_loan_item_returned_qty CHECK (
        returned_quantity >= 0 AND returned_quantity <= quantity
    ),
    CONSTRAINT ck_loan_item_fine_non_negative CHECK (fine >= 0)
);

-- ============================================================
-- 4) NEGOCIO: APOYO (kits, mantenimiento, compensaciones)
-- ============================================================

CREATE TABLE IF NOT EXISTS kit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_kit_name UNIQUE (name),
    CONSTRAINT ck_kit_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS kit_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kit_id BIGINT NOT NULL REFERENCES kit(id) ON DELETE RESTRICT,
    item_id BIGINT NOT NULL REFERENCES item(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_kit_item UNIQUE (kit_id, item_id),
    CONSTRAINT ck_kit_item_quantity_positive CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS maintenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES item(id) ON DELETE RESTRICT,
    stock_id BIGINT REFERENCES stock(id) ON DELETE RESTRICT,
    processed_by_user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ,
    description TEXT,
    cost NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_maintenance_cost_non_negative CHECK (cost >= 0),
    CONSTRAINT ck_maintenance_date_range CHECK (end_at IS NULL OR end_at >= start_at)
);

CREATE TABLE IF NOT EXISTS payment_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_payment_method_name UNIQUE (name),
    CONSTRAINT ck_payment_method_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS compensation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_item_id BIGINT NOT NULL REFERENCES loan_item(id) ON DELETE RESTRICT,
    processed_by_user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    borrower_user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    payment_method_id BIGINT NOT NULL REFERENCES payment_method(id) ON DELETE RESTRICT,
    amount_paid NUMERIC(12,2) NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL,
    observations TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_compensation_amount_paid_non_negative CHECK (amount_paid >= 0)
);

COMMIT;

-- ============================================================
-- Indices
-- ============================================================

BEGIN;

-- Seguridad
CREATE INDEX IF NOT EXISTS ix_person_group_person_id ON person_group(person_id);
CREATE INDEX IF NOT EXISTS ix_person_group_group_id ON person_group(group_id);
CREATE INDEX IF NOT EXISTS ix_user_person_id ON "user"(person_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_user_id ON user_profile(user_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_profile_id ON user_profile(profile_id);
CREATE INDEX IF NOT EXISTS ix_option_profile_profile_id ON option_profile(profile_id);
CREATE INDEX IF NOT EXISTS ix_option_profile_option_id ON option_profile(option_id);
CREATE INDEX IF NOT EXISTS ix_menu_subsystem_id ON menu(subsystem_id);
CREATE INDEX IF NOT EXISTS ix_option_menu_option_id ON option_menu(option_id);
CREATE INDEX IF NOT EXISTS ix_option_menu_menu_id ON option_menu(menu_id);
CREATE INDEX IF NOT EXISTS ix_subsystem_class_subsystem_id ON subsystem_class(subsystem_id);
CREATE INDEX IF NOT EXISTS ix_subsystem_class_class_id ON subsystem_class(class_id);
CREATE INDEX IF NOT EXISTS ix_class_method_class_id ON class_method(class_id);
CREATE INDEX IF NOT EXISTS ix_class_method_method_id ON class_method(method_id);
CREATE INDEX IF NOT EXISTS ix_method_profile_method_id ON method_profile(method_id);
CREATE INDEX IF NOT EXISTS ix_method_profile_profile_id ON method_profile(profile_id);
CREATE INDEX IF NOT EXISTS ix_transaction_subsystem_id ON "transaction"(subsystem_id);
CREATE INDEX IF NOT EXISTS ix_transaction_class_id ON "transaction"(class_id);
CREATE INDEX IF NOT EXISTS ix_transaction_method_id ON "transaction"(method_id);
CREATE INDEX IF NOT EXISTS ix_audit_user_id ON audit(user_id);
CREATE INDEX IF NOT EXISTS ix_audit_type_id ON audit(type_id);
CREATE INDEX IF NOT EXISTS ix_notification_user_id ON notification(user_id);
CREATE INDEX IF NOT EXISTS ix_notification_type_id ON notification(type_id);

-- Negocio
CREATE INDEX IF NOT EXISTS ix_item_category_id ON item(category_id);
CREATE INDEX IF NOT EXISTS ix_item_condition_id ON item(condition_id);
CREATE INDEX IF NOT EXISTS ix_item_status_id ON item(status_id);
CREATE INDEX IF NOT EXISTS ix_location_parent_id ON location(parent_id);
CREATE INDEX IF NOT EXISTS ix_stock_item_id ON stock(item_id);
CREATE INDEX IF NOT EXISTS ix_stock_location_id ON stock(location_id);
CREATE INDEX IF NOT EXISTS ix_loan_borrower_user_id ON loan(borrower_user_id);
CREATE INDEX IF NOT EXISTS ix_loan_processed_by_user_id ON loan(processed_by_user_id);
CREATE INDEX IF NOT EXISTS ix_loan_status_id ON loan(status_id);
CREATE INDEX IF NOT EXISTS ix_loan_booked_at ON loan(booked_at);
CREATE INDEX IF NOT EXISTS ix_loan_item_loan_id ON loan_item(loan_id);
CREATE INDEX IF NOT EXISTS ix_loan_item_stock_id ON loan_item(stock_id);
CREATE INDEX IF NOT EXISTS ix_kit_item_kit_id ON kit_item(kit_id);
CREATE INDEX IF NOT EXISTS ix_kit_item_item_id ON kit_item(item_id);
CREATE INDEX IF NOT EXISTS ix_maintenance_item_id ON maintenance(item_id);
CREATE INDEX IF NOT EXISTS ix_maintenance_stock_id ON maintenance(stock_id);
CREATE INDEX IF NOT EXISTS ix_maintenance_processed_by_user_id ON maintenance(processed_by_user_id);
CREATE INDEX IF NOT EXISTS ix_compensation_loan_item_id ON compensation(loan_item_id);
CREATE INDEX IF NOT EXISTS ix_compensation_borrower_user_id ON compensation(borrower_user_id);

-- Soft delete + unicidad funcional
CREATE UNIQUE INDEX IF NOT EXISTS uq_item_code_active
    ON item (code)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_person_document_id_active
    ON person (document_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email_active
    ON "user" (email)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_name_lower_active
    ON "user" (LOWER(name))
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_profile_name_lower_active
    ON profile (LOWER(name));

-- updated_at automatico
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    t TEXT;
    trg_name TEXT;
    tables TEXT[] := ARRAY[
        'group_type', 'person', 'user', 'transaction',
        'item_category', 'item', 'stock',
        'loan', 'loan_item',
        'kit', 'kit_item', 'maintenance', 'compensation'
    ];
BEGIN
    FOREACH t IN ARRAY tables
    LOOP
        trg_name := 'trg_' || t || '_updated_at';
        EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', trg_name, t);
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            trg_name,
            t
        );
    END LOOP;
END;
$$;

COMMIT;
