const sanitizeRegexCatalog = [
  {
    key: 'username_whitespace',
    pattern: '\\s',
    flags: 'g',
    mode: 'deny',
    target: 'value',
    description: 'No permite espacios en username',
  },
  {
    key: 'xss_script_tag',
    pattern: '<\\s*script\\b[^>]*>(.*?)<\\s*\\/\\s*script\\s*>',
    flags: 'i',
    mode: 'deny',
    target: 'value',
    description: 'Bloquea tags script completos',
  },
  {
    key: 'xss_javascript_protocol',
    pattern: 'javascript\\s*:',
    flags: 'i',
    mode: 'deny',
    target: 'value',
    description: 'Bloquea protocolo javascript:',
  },
  {
    key: 'xss_inline_handler',
    pattern: 'on[a-z]+\\s*=',
    flags: 'i',
    mode: 'deny',
    target: 'value',
    description: 'Bloquea handlers inline como onerror=',
  },
  {
    key: 'control_chars',
    pattern: '[\\u0000-\\u001F\\u007F]',
    flags: 'g',
    mode: 'deny',
    target: 'value',
    description: 'Bloquea caracteres de control invisibles',
  },
  {
    key: 'sql_union_select',
    pattern: '(?:^|\\W)union\\s+all?\\s+select(?:\\W|$)',
    flags: 'i',
    mode: 'deny',
    target: 'value',
    description: 'Bloquea patrones clásicos de SQL injection',
  },
  {
    key: 'sql_comment_sequence',
    pattern: '(?:--|\\/\\*|\\*\\/|#)',
    flags: 'g',
    mode: 'deny',
    target: 'value',
    description: 'Bloquea secuencias de comentarios SQL',
  },
  {
    key: 'command_injection_chain',
    pattern: '(?:\\|\\||&&|;|`|\\$\\()',
    flags: 'g',
    mode: 'deny',
    target: 'value',
    description: 'Bloquea operadores de chaining/comando',
  },
  {
    key: 'path_traversal',
    pattern: '(?:\\.\\.[\\/\\\\])+',
    flags: 'g',
    mode: 'deny',
    target: 'value',
    description: 'Bloquea path traversal',
  },
  {
    key: 'sensitive_property_name',
    pattern:
      '(?:^|_|\\b)(password|pass|passwd|pwd|secret|passphrase|token|access_token|refresh_token|auth_token|session_id|sid|jwt|api_key|apikey|secret_key|client_secret|private_key|app_secret|credit_card|card_number|cvv|cvc|exp_month|exp_year|account_number|iban|routing_number|swift_code|ssn|tax_id|dni|ci|passport|email|phone|address|db|api|key)(?:$|_|\\b)',
    flags: 'i',
    mode: 'detect',
    target: 'property',
    description: 'Detecta nombres de propiedades potencialmente sensibles',
  },
  {
    key: 'sensitive_jwt_value',
    pattern: '^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$',
    flags: '',
    mode: 'detect',
    target: 'value',
    description: 'Detecta estructura de token JWT',
  },
  {
    key: 'sensitive_bearer_token',
    pattern: '^Bearer\\s+[A-Za-z0-9._~+\\/-]+=*$',
    flags: 'i',
    mode: 'detect',
    target: 'value',
    description: 'Detecta token Bearer',
  },
  {
    key: 'sensitive_private_key_block',
    pattern: '-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----',
    flags: 'i',
    mode: 'detect',
    target: 'value',
    description: 'Detecta bloque de private key PEM',
  },
  {
    key: 'sensitive_high_entropy_keylike',
    pattern: '^[A-Za-z0-9+/_=-]{32,}$',
    flags: '',
    mode: 'detect',
    target: 'value',
    description: 'Detecta cadenas tipo key/token de alta longitud',
  },
  {
    key: 'sensitive_credit_card_like',
    pattern: '^(?:\\d[ -]*?){13,19}$',
    flags: '',
    mode: 'detect',
    target: 'value',
    description: 'Detecta número tipo tarjeta',
  },
  {
    key: 'sensitive_iban_like',
    pattern: '^[A-Z]{2}\\d{2}[A-Z0-9]{11,30}$',
    flags: 'i',
    mode: 'detect',
    target: 'value',
    description: 'Detecta IBAN',
  },
  {
    key: 'sensitive_email_like',
    pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
    flags: 'i',
    mode: 'detect',
    target: 'value',
    description: 'Detecta valor tipo email',
  },
  {
    key: 'sensitive_phone_like',
    pattern: '^\\+?[0-9][0-9\\s().-]{6,}$',
    flags: '',
    mode: 'detect',
    target: 'value',
    description: 'Detecta valor tipo teléfono',
  },
];

export default sanitizeRegexCatalog;
