export const loanCatalog = {
  equipos: [
    {
      id: "eq-1",
      titulo: "Osciloscopio Tektronix",
      descripcion: "Equipo de medición para análisis de señales.",
      tipo: "Equipo de laboratorio",
      condicion: "Excelente",
    },
    {
      id: "eq-2",
      titulo: "Multímetro Fluke",
      descripcion: "Instrumento para medición de voltaje y resistencia.",
      tipo: "Equipo de medición",
      condicion: "Bueno",
    },
    {
      id: "eq-3",
      titulo: "Laptop Lenovo",
      descripcion: "Portátil asignable para actividades académicas.",
      tipo: "Equipo portátil",
      condicion: "Usado",
    },
    {
      id: "eq-3",
      titulo: "Laptop Lenovo",
      descripcion: "Portátil asignable para actividades académicas.",
      tipo: "Equipo portátil",
      condicion: "Usado",
    },
    {
      id: "eq-456465",
      titulo: "Laptop Lenovo",
      descripcion: "Portátil asignable para actividades académicas.",
      tipo: "Equipo portátil",
      condicion: "Usado",
    },
    {
      id: "eq-65",
      titulo: "Laptop Lenovo",
      descripcion: "Portátil asignable para actividades académicas.",
      tipo: "Equipo portátil",
      condicion: "Usado",
    },
    {
      id: "eq-6",
      titulo: "Laptop Lenovo",
      descripcion: "Portátil asignable para actividades académicas.",
      tipo: "Equipo portátil",
      condicion: "Usado",
    },
    {
      id: "eq-5",
      titulo: "Laptop Lenovo",
      descripcion: "Portátil asignable para actividades académicas.",
      tipo: "Equipo portátil",
      condicion: "Usado",
    },
  ],
  insumos: [
    {
      id: "in-1",
      titulo: "Resistencias 1kΩ",
      descripcion: "Paquete de resistencias para prototipado.",
      tipo: "Insumo electrónico",
      condicion: "Nuevo",
    },
    {
      id: "in-2",
      titulo: "Protoboard",
      descripcion: "Base de montaje para pruebas de circuito.",
      tipo: "Insumo de montaje",
      condicion: "Bueno",
    },
    {
      id: "in-3",
      titulo: "Cable Dupont",
      descripcion: "Set de cables para conexión rápida.",
      tipo: "Insumo de conexión",
      condicion: "Nuevo",
    },
  ],
};
