-- ============================================================
-- PostgreSQL DDL generado a partir de los diagramas:
-- 1) BO SCHEME
-- 2) SECURITY SCHEME
--
-- Nota sobre palabras reservadas:
--   Se crean con comillas dobles: "user", "group", "option",
--   "class", "transaction"
--   (en consultas SQL deberán referenciarse con comillas).
-- ============================================================

\set ON_ERROR_STOP on
\connect postgres

-- Crea la BD de trabajo si no existe (idempotente para re-ejecuciones)
SELECT 'CREATE DATABASE webii'
WHERE NOT EXISTS (
    SELECT 1 FROM pg_database WHERE datname = 'webii'
)\gexec

\connect webii

-- Asegura que el esquema por defecto sea public, incluso si el search_path venía vacío.
SELECT pg_catalog.set_config('search_path', 'public', false);

-- (Opcional) Descomenta para reiniciar todo en desarrollo.
-- DROP TABLE IF EXISTS
--   return_status,
--   movement_detail,
--   movement,
--   inventory,
--   item,
--   category,
--   category_type,
--   property_item,
--   property,
--   location,
--   movement_type,
--   lapse,
--   audit,
--   notification,
--   person_group,
--   "group",
--   user_profile,
--   option_profile,
--   option_menu,
--   method_profile,
--   method_class,
--   class_subsystem,
--   "transaction",
--   menu,
--   "option",
--   profile,
--   "user",
--   person,
--   subsystem,
--   "class",
--   method
-- CASCADE;

-- =========================
-- BO SCHEME (Catálogo/Inventario/Movimientos)
-- =========================

CREATE TABLE IF NOT EXISTS category_type (
                                             category_type_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             category_type_de  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
                                        category_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        category_de        TEXT NOT NULL,
                                        category_type_id   BIGINT NOT NULL REFERENCES category_type(category_type_id)
    );

CREATE INDEX IF NOT EXISTS ix_category_category_type_id ON category(category_type_id);

CREATE TABLE IF NOT EXISTS item (
                                    item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    item_cod     TEXT NOT NULL,
                                    item_na      TEXT NOT NULL,
                                    category_id  BIGINT NOT NULL REFERENCES category(category_id)
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_item_item_cod ON item(item_cod);
CREATE INDEX IF NOT EXISTS ix_item_category_id ON item(category_id);

CREATE TABLE IF NOT EXISTS property (
                                        property_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        property_de   TEXT NOT NULL,
                                        property_val  TEXT
);

CREATE TABLE IF NOT EXISTS property_item (
                                             property_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             property_item_de  TEXT,
                                             property_id       BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    item_id           BIGINT NOT NULL REFERENCES item(item_id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS ix_property_item_property_id ON property_item(property_id);
CREATE INDEX IF NOT EXISTS ix_property_item_item_id ON property_item(item_id);

CREATE TABLE IF NOT EXISTS location (
                                        location_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        location_de  TEXT NOT NULL,
                                        location_sh  TEXT,
                                        location_dr  TEXT
);

CREATE TABLE IF NOT EXISTS inventory (
                                         inventory_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         inventory_am          INTEGER NOT NULL DEFAULT 0,
                                         inventory_update_dt   TIMESTAMPTZ,
                                         location_id           BIGINT NOT NULL REFERENCES location(location_id) ON DELETE RESTRICT,
    item_id               BIGINT NOT NULL REFERENCES item(item_id) ON DELETE RESTRICT,
    CONSTRAINT ux_inventory_location_item UNIQUE (location_id, item_id)
    );

CREATE INDEX IF NOT EXISTS ix_inventory_location_id ON inventory(location_id);
CREATE INDEX IF NOT EXISTS ix_inventory_item_id ON inventory(item_id);

CREATE TABLE IF NOT EXISTS lapse (
                                     lapse_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     lapse_de        TEXT NOT NULL,
                                     lapse_act       BOOLEAN NOT NULL DEFAULT TRUE,
                                     lapse_start_dt  TIMESTAMPTZ,
                                     lapse_close_dt  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS movement_type (
                                             movement_type_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             movement_type_de  TEXT NOT NULL
);

-- =========================
-- BO SCHEME (Personas y Grupos)
-- =========================

CREATE TABLE IF NOT EXISTS person (
                                      person_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      person_ci   TEXT NOT NULL,
                                      person_na   TEXT NOT NULL,
                                      person_ln   TEXT,
                                      person_em   TEXT,
                                      person_ph   TEXT,
                                      person_deg  TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_person_person_ci ON person(person_ci);

CREATE TABLE IF NOT EXISTS "group" (
                                       group_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       group_de  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS person_group (
                                            person_group_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            group_id         BIGINT NOT NULL REFERENCES "group"(group_id) ON DELETE CASCADE,
    person_id        BIGINT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    CONSTRAINT ux_person_group UNIQUE (group_id, person_id)
    );

CREATE INDEX IF NOT EXISTS ix_person_group_group_id ON person_group(group_id);
CREATE INDEX IF NOT EXISTS ix_person_group_person_id ON person_group(person_id);

-- =========================
-- SECURITY SCHEME (Usuarios/Permisos)
-- =========================

CREATE TABLE IF NOT EXISTS profile (
                                       profile_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       profile_de  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "user" (
                                      user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      user_na    TEXT NOT NULL,
                                      user_pw    TEXT NOT NULL,
                                      user_sol   BOOLEAN DEFAULT true,
                                      person_id  BIGINT REFERENCES person(person_id) ON DELETE SET NULL
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_user_user_na ON "user"(user_na);
CREATE INDEX IF NOT EXISTS ix_user_person_id ON "user"(person_id);

CREATE TABLE IF NOT EXISTS user_profile (
                                            user_profile_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            profile_id       BIGINT NOT NULL REFERENCES profile(profile_id) ON DELETE CASCADE,
    user_id          BIGINT NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT ux_user_profile UNIQUE (profile_id, user_id)
    );

CREATE INDEX IF NOT EXISTS ix_user_profile_profile_id ON user_profile(profile_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_user_id ON user_profile(user_id);

CREATE TABLE IF NOT EXISTS "option" (
                                        option_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        option_de  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS option_profile (
                                              option_profile_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              profile_id         BIGINT NOT NULL REFERENCES profile(profile_id) ON DELETE CASCADE,
    option_id          BIGINT NOT NULL REFERENCES "option"(option_id) ON DELETE CASCADE,
    CONSTRAINT ux_option_profile UNIQUE (profile_id, option_id)
    );

CREATE INDEX IF NOT EXISTS ix_option_profile_profile_id ON option_profile(profile_id);
CREATE INDEX IF NOT EXISTS ix_option_profile_option_id ON option_profile(option_id);

CREATE TABLE IF NOT EXISTS subsystem (
                                         subsystem_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         subsystem_na  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS menu (
                                    menu_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    menu_na       TEXT NOT NULL,
                                    subsystem_id  BIGINT NOT NULL REFERENCES subsystem(subsystem_id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS ix_menu_subsystem_id ON menu(subsystem_id);

CREATE TABLE IF NOT EXISTS option_menu (
                                           option_menu_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           option_id       BIGINT NOT NULL REFERENCES "option"(option_id) ON DELETE CASCADE,
    menu_id         BIGINT NOT NULL REFERENCES menu(menu_id) ON DELETE CASCADE,
    CONSTRAINT ux_option_menu UNIQUE (option_id, menu_id)
    );

CREATE INDEX IF NOT EXISTS ix_option_menu_option_id ON option_menu(option_id);
CREATE INDEX IF NOT EXISTS ix_option_menu_menu_id ON option_menu(menu_id);

CREATE TABLE IF NOT EXISTS "class" (
                                       class_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       class_na  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS class_subsystem (
                                               class_subsystem_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               class_id            BIGINT NOT NULL REFERENCES "class"(class_id) ON DELETE CASCADE,
    subsystem_id        BIGINT NOT NULL REFERENCES subsystem(subsystem_id) ON DELETE CASCADE,
    CONSTRAINT ux_class_subsystem UNIQUE (class_id, subsystem_id)
    );

CREATE INDEX IF NOT EXISTS ix_class_subsystem_class_id ON class_subsystem(class_id);
CREATE INDEX IF NOT EXISTS ix_class_subsystem_subsystem_id ON class_subsystem(subsystem_id);

CREATE TABLE IF NOT EXISTS method (
                                      method_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      method_na  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS method_class (
                                            method_class_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            method_id        BIGINT NOT NULL REFERENCES method(method_id) ON DELETE CASCADE,
    class_id         BIGINT NOT NULL REFERENCES "class"(class_id) ON DELETE CASCADE,
    CONSTRAINT ux_method_class UNIQUE (method_id, class_id)
    );

CREATE INDEX IF NOT EXISTS ix_method_class_method_id ON method_class(method_id);
CREATE INDEX IF NOT EXISTS ix_method_class_class_id ON method_class(class_id);

CREATE TABLE IF NOT EXISTS method_profile (
                                              method_profile_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              profile_id         BIGINT NOT NULL REFERENCES profile(profile_id) ON DELETE CASCADE,
    method_id          BIGINT NOT NULL REFERENCES method(method_id) ON DELETE CASCADE,
    CONSTRAINT ux_method_profile UNIQUE (profile_id, method_id)
    );

CREATE INDEX IF NOT EXISTS ix_method_profile_profile_id ON method_profile(profile_id);
CREATE INDEX IF NOT EXISTS ix_method_profile_method_id ON method_profile(method_id);

CREATE TABLE IF NOT EXISTS "transaction" (
                                             transaction_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             transaction_nu  INTEGER NOT NULL,
                                             method_id       BIGINT NOT NULL REFERENCES method(method_id) ON DELETE RESTRICT,
    class_id        BIGINT NOT NULL REFERENCES "class"(class_id) ON DELETE RESTRICT,
    subsystem_id    BIGINT NOT NULL REFERENCES subsystem(subsystem_id) ON DELETE RESTRICT
    );

CREATE INDEX IF NOT EXISTS ix_transaction_method_id ON "transaction"(method_id);
CREATE INDEX IF NOT EXISTS ix_transaction_class_id ON "transaction"(class_id);
CREATE INDEX IF NOT EXISTS ix_transaction_subsystem_id ON "transaction"(subsystem_id);

-- =========================
-- BO SCHEME (Movimientos)
-- =========================
-- Nota: en el diagrama el campo se llama transaction_type_id pero apunta a movement_type.
-- Se respeta el nombre del campo tal como aparece.
CREATE TABLE IF NOT EXISTS movement (
                                        movement_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        movement_booking_dt           TIMESTAMPTZ,
                                        movement_estimated_return_dt  TIMESTAMPTZ,
                                        movement_ob                   TEXT,
                                        user_id                       BIGINT NOT NULL REFERENCES "user"(user_id) ON DELETE RESTRICT,
    transaction_type_id           BIGINT NOT NULL REFERENCES movement_type(movement_type_id) ON DELETE RESTRICT,
    lapse_id                      BIGINT NOT NULL REFERENCES lapse(lapse_id) ON DELETE RESTRICT
    );

CREATE INDEX IF NOT EXISTS ix_movement_user_id ON movement(user_id);
CREATE INDEX IF NOT EXISTS ix_movement_transaction_type_id ON movement(transaction_type_id);
CREATE INDEX IF NOT EXISTS ix_movement_lapse_id ON movement(lapse_id);

CREATE TABLE IF NOT EXISTS movement_detail (
                                               movement_detail_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               movement_detail_dt  TIMESTAMPTZ,
                                               movement_detail_am  INTEGER NOT NULL DEFAULT 1,
                                               movement_detail_fi  NUMERIC(12,2) NOT NULL DEFAULT 0,
    movement_detail_ob  TEXT,
    inventory_id        BIGINT NOT NULL REFERENCES inventory(inventory_id) ON DELETE RESTRICT,
    movement_id         BIGINT NOT NULL REFERENCES movement(movement_id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS ix_movement_detail_inventory_id ON movement_detail(inventory_id);
CREATE INDEX IF NOT EXISTS ix_movement_detail_movement_id ON movement_detail(movement_id);

CREATE TABLE IF NOT EXISTS return_status (
                                             return_status_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             return_status_dt     TIMESTAMPTZ,
                                             return_status_de     TEXT NOT NULL,
                                             return_status_ob     TEXT,
                                             movement_detail_id   BIGINT NOT NULL REFERENCES movement_detail(movement_detail_id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS ix_return_status_movement_detail_id ON return_status(movement_detail_id);

-- =========================
-- BO SCHEME (Auditoría / Notificaciones)
-- =========================
CREATE TABLE IF NOT EXISTS audit (
                                     audit_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     audit_tab  TEXT NOT NULL,
                                     audit_met  TEXT NOT NULL,
                                     audit_dt   DATE,
                                     audit_tm   TIME,
                                     audit_det  TEXT,
                                     user_id    BIGINT NOT NULL REFERENCES "user"(user_id) ON DELETE RESTRICT
    );

CREATE INDEX IF NOT EXISTS ix_audit_user_id ON audit(user_id);

CREATE TABLE IF NOT EXISTS notification (
                                            notification_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            notification_ty   TEXT NOT NULL,
                                            notification_tit  TEXT NOT NULL,
                                            notification_msg  TEXT NOT NULL,
                                            notification_dt   TIMESTAMPTZ,
                                            user_id           BIGINT NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS ix_notification_user_id ON notification(user_id);
