-- ============================================================
-- schema.sql - Migraciones versionadas (simulacion Flyway)
-- Proyecto: Web II
-- Motor: PostgreSQL
-- ============================================================

-- ============================================================
-- V1__Initial_Schema.sql
-- Objetivo: Estructura base normalizada + reglas de integridad.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Dominios de validacion institucional
-- ------------------------------------------------------------
CREATE DOMAIN email_address AS VARCHAR(150)
    CHECK (VALUE ~* '^[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}$');

CREATE DOMAIN document_identifier AS VARCHAR(30)
    CHECK (VALUE ~ '^[A-Za-z0-9\-]{5,30}$');

CREATE DOMAIN phone_number AS VARCHAR(30)
    CHECK (VALUE ~ '^\+?[0-9 ()\-]{7,20}$');

-- ------------------------------------------------------------
-- Convencion de metacampos compartidos
-- name, description, is_active, created_at, updated_at
-- Se aplica a catalogos y entidades maestras que lo ameritan.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS category_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_category_type_name UNIQUE (name),
    CONSTRAINT ck_category_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    type_id BIGINT NOT NULL REFERENCES category_type(id) ON DELETE RESTRICT, -- evita borrado accidental del tipo en uso
    CONSTRAINT uq_category_name_type UNIQUE (name, type_id),
    CONSTRAINT ck_category_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS feature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_feature_name UNIQUE (name),
    CONSTRAINT ck_feature_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    cost NUMERIC(12,2) NOT NULL DEFAULT 0,
    acquisition_date DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    category_id BIGINT NOT NULL REFERENCES category(id) ON DELETE RESTRICT, -- evita eliminar categoria con inventario historico
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_item_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_item_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_item_cost_non_negative CHECK (cost >= 0)
);

CREATE TABLE IF NOT EXISTS item_feature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT,
    feature_id BIGINT NOT NULL REFERENCES feature(id) ON DELETE RESTRICT, -- conserva catalogo de caracteristicas en uso
    item_id BIGINT NOT NULL REFERENCES item(id) ON DELETE RESTRICT, -- se evita cascada por trazabilidad historica
    CONSTRAINT uq_item_feature_pair UNIQUE (feature_id, item_id)
);

CREATE TABLE IF NOT EXISTS location_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_location_type_name UNIQUE (name),
    CONSTRAINT ck_location_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    parent_id BIGINT REFERENCES location(id) ON DELETE SET NULL, -- al borrar padre, el hijo mantiene trazabilidad sin romper FK
    type_id BIGINT REFERENCES location_type(id) ON DELETE SET NULL, -- se conserva ubicacion aunque el tipo sea descontinuado
    CONSTRAINT ck_location_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount INTEGER NOT NULL DEFAULT 0,
    location_id BIGINT NOT NULL REFERENCES location(id) ON DELETE RESTRICT, -- evita eliminar ubicacion con stock
    item_id BIGINT NOT NULL REFERENCES item(id) ON DELETE RESTRICT, -- evita eliminar item con stock
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_inventory_location_item UNIQUE (location_id, item_id),
    CONSTRAINT ck_inventory_amount_non_negative CHECK (amount >= 0)
);

CREATE TABLE IF NOT EXISTS period_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_period_type_name UNIQUE (name),
    CONSTRAINT ck_period_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    start_date DATE,
    end_date DATE,
    type_id BIGINT NOT NULL REFERENCES period_type(id) ON DELETE RESTRICT, -- evita eliminar tipo de periodo utilizado
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_period_name_type UNIQUE (name, type_id),
    CONSTRAINT ck_period_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_period_date_range CHECK (
        end_date IS NULL OR start_date IS NULL OR end_date >= start_date
    )
);

CREATE TABLE IF NOT EXISTS movement_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_movement_type_name UNIQUE (name),
    CONSTRAINT ck_movement_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id document_identifier NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone phone_number,
    degree VARCHAR(150),
    address TEXT,
    birth_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_person_first_name_not_blank CHECK (btrim(first_name) <> ''),
    CONSTRAINT ck_person_last_name_not_blank CHECK (btrim(last_name) <> '')
);

CREATE TABLE IF NOT EXISTS person_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id) ON DELETE RESTRICT, -- se bloquea borrado de persona con asignaciones
    CONSTRAINT uq_person_group_person UNIQUE (person_id)
);

-- Definicion de la tabla "user"
CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    email email_address,
    password_hash TEXT NOT NULL,
    is_solvency BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    person_id BIGINT REFERENCES person(id) ON DELETE SET NULL, -- se conserva usuario aunque persona asociada se desactive
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_user_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_user_password_hash_not_blank CHECK (btrim(password_hash) <> '')
);

CREATE TABLE IF NOT EXISTS movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_date TIMESTAMPTZ,
    estimated_return_date TIMESTAMPTZ,
    actual_return_date TIMESTAMPTZ,
    observations TEXT,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT, -- evita borrar usuario con movimientos historicos
    type_id BIGINT NOT NULL REFERENCES movement_type(id) ON DELETE RESTRICT, -- mantiene consistencia del tipo
    period_id BIGINT NOT NULL REFERENCES period(id) ON DELETE RESTRICT, -- mantiene consistencia temporal academica
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_movement_date_order CHECK (
        actual_return_date IS NULL OR booking_date IS NULL OR actual_return_date >= booking_date
    )
);

CREATE TABLE IF NOT EXISTS movement_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_date TIMESTAMPTZ,
    amount INTEGER NOT NULL DEFAULT 1,
    fine NUMERIC(12,2) NOT NULL DEFAULT 0,
    observations TEXT,
    inventory_id BIGINT NOT NULL REFERENCES inventory(id) ON DELETE RESTRICT, -- evita borrar inventario con historial transaccional
    movement_id BIGINT NOT NULL REFERENCES movement(id) ON DELETE RESTRICT, -- evita cascada accidental en historial
    CONSTRAINT ck_movement_detail_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_movement_detail_fine_non_negative CHECK (fine >= 0)
);

CREATE TABLE IF NOT EXISTS return_status_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_return_status_type_name UNIQUE (name),
    CONSTRAINT ck_return_status_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS return_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id BIGINT NOT NULL REFERENCES return_status_type(id) ON DELETE RESTRICT, -- catalogo controlado de estados
    status_date TIMESTAMPTZ,
    observations TEXT,
    movement_detail_id BIGINT NOT NULL REFERENCES movement_detail(id) ON DELETE RESTRICT, -- conserva historial de devolucion
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_audit_type_name UNIQUE (name),
    CONSTRAINT ck_audit_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(100) NOT NULL,
    method VARCHAR(50) NOT NULL,
    event_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    details TEXT,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT, -- evita borrar usuario con auditoria
    type_id BIGINT NOT NULL REFERENCES audit_type(id) ON DELETE RESTRICT, -- mantiene catalogo historico
    CONSTRAINT ck_audit_entity_name_not_blank CHECK (btrim(entity_name) <> ''),
    CONSTRAINT ck_audit_method_not_blank CHECK (btrim(method) <> '')
);

CREATE TABLE IF NOT EXISTS notification_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_notification_type_name UNIQUE (name),
    CONSTRAINT ck_notification_type_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    sent_at TIMESTAMPTZ,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT, -- evita borrado de receptor con historial
    type_id BIGINT NOT NULL REFERENCES notification_type(id) ON DELETE RESTRICT, -- mantiene tipologia estable
    CONSTRAINT ck_notification_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT ck_notification_message_not_blank CHECK (btrim(message) <> '')
);

CREATE TABLE IF NOT EXISTS profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_profile_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT, -- evita eliminar usuarios con perfiles asignados
    profile_id BIGINT NOT NULL REFERENCES profile(id) ON DELETE RESTRICT, -- evita eliminar perfiles en uso
    CONSTRAINT uq_user_profile UNIQUE (user_id, profile_id)
);

-- Definicion de la tabla "option"
CREATE TABLE IF NOT EXISTS "option" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_option_name UNIQUE (name),
    CONSTRAINT ck_option_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS option_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profile(id) ON DELETE RESTRICT, -- seguridad: no borrar perfil en uso
    option_id BIGINT NOT NULL REFERENCES "option"(id) ON DELETE RESTRICT, -- seguridad: no borrar opcion asignada
    CONSTRAINT uq_option_profile UNIQUE (profile_id, option_id)
);

CREATE TABLE IF NOT EXISTS subsystem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_subsystem_name UNIQUE (name),
    CONSTRAINT ck_subsystem_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    subsystem_id BIGINT NOT NULL REFERENCES subsystem(id) ON DELETE RESTRICT, -- evita cascada en estructura de navegacion
    CONSTRAINT uq_menu_name_subsystem UNIQUE (name, subsystem_id),
    CONSTRAINT ck_menu_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS option_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id BIGINT NOT NULL REFERENCES "option"(id) ON DELETE RESTRICT, -- mantiene mapa de navegacion estable
    menu_id BIGINT NOT NULL REFERENCES menu(id) ON DELETE RESTRICT, -- mantiene menu referenciado
    CONSTRAINT uq_option_menu UNIQUE (option_id, menu_id)
);

-- Definicion de la tabla "class"
CREATE TABLE IF NOT EXISTS "class" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_class_name UNIQUE (name),
    CONSTRAINT ck_class_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS subsystem_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subsystem_id BIGINT NOT NULL REFERENCES subsystem(id) ON DELETE RESTRICT, -- evita borrado de subsistema en uso
    class_id BIGINT NOT NULL REFERENCES "class"(id) ON DELETE RESTRICT, -- evita borrado de clase en uso
    CONSTRAINT uq_subsystem_class UNIQUE (subsystem_id, class_id)
);

CREATE TABLE IF NOT EXISTS "method" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_method_name UNIQUE (name),
    CONSTRAINT ck_method_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS class_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL REFERENCES "class"(id) ON DELETE RESTRICT, -- evita borrado de clase con metodos asociados
    method_id BIGINT NOT NULL REFERENCES "method"(id) ON DELETE RESTRICT, -- evita borrado de metodo con dependencias
    CONSTRAINT uq_class_method UNIQUE (class_id, method_id)
);

CREATE TABLE IF NOT EXISTS method_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_id BIGINT NOT NULL REFERENCES "method"(id) ON DELETE RESTRICT, -- evita perdida de matriz de autorizacion
    profile_id BIGINT NOT NULL REFERENCES profile(id) ON DELETE RESTRICT, -- evita perdida de matriz de autorizacion
    CONSTRAINT uq_method_profile UNIQUE (method_id, profile_id)
);

-- Definicion de la tabla "transaction"
CREATE TABLE IF NOT EXISTS "transaction" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subsystem_id BIGINT NOT NULL REFERENCES subsystem(id) ON DELETE RESTRICT, -- seguridad: no borrar subsistema con transacciones
    class_id BIGINT NOT NULL REFERENCES "class"(id) ON DELETE RESTRICT, -- seguridad: no borrar clase con transacciones
    method_id BIGINT NOT NULL REFERENCES "method"(id) ON DELETE RESTRICT, -- seguridad: no borrar metodo con transacciones
    CONSTRAINT uq_transaction_scope UNIQUE (subsystem_id, class_id, method_id)
);

-- ------------------------------------------------------------
-- Documentacion de tablas y campos con ejemplos de caso real
-- ------------------------------------------------------------
COMMENT ON TABLE category_type IS 'Catalogo de tipos de categoria. Ejemplo real: BOOK, DEVICE, LAB_MATERIAL.';
COMMENT ON COLUMN category_type.id IS 'Identificador del tipo de categoria. Ejemplo real: 1 para BOOK.';
COMMENT ON COLUMN category_type.name IS 'Nombre del tipo. Ejemplo real: BOOK, DEVICE, LAB_MATERIAL.';
COMMENT ON COLUMN category_type.description IS 'Descripcion del tipo. Ejemplo real: Material bibliografico.';
COMMENT ON COLUMN category_type.is_active IS 'Estado del tipo. Ejemplo real: TRUE para tipos vigentes.';
COMMENT ON COLUMN category_type.created_at IS 'Fecha de creacion. Ejemplo real: 2026-03-21 09:15:00+00.';
COMMENT ON COLUMN category_type.updated_at IS 'Fecha de ultima actualizacion. Ejemplo real: 2026-03-22 10:40:00+00.';

COMMENT ON TABLE category IS 'Categorias de inventario. Ejemplo real: Algebra Lineal, Laptop, Proyector.';
COMMENT ON COLUMN category.id IS 'Identificador de categoria. Ejemplo real: 25.';
COMMENT ON COLUMN category.name IS 'Nombre de categoria. Ejemplo real: Laptop.';
COMMENT ON COLUMN category.description IS 'Descripcion de categoria. Ejemplo real: Equipos portatiles para prestamo.';
COMMENT ON COLUMN category.type_id IS 'FK al tipo de categoria. Ejemplo real: type_id=2 (DEVICE).';

COMMENT ON TABLE feature IS 'Caracteristicas tecnicas que puede tener un item. Ejemplo real: RAM, COLOR, AUTOR.';
COMMENT ON COLUMN feature.id IS 'Identificador de caracteristica. Ejemplo real: 3.';
COMMENT ON COLUMN feature.name IS 'Nombre de la caracteristica. Ejemplo real: RAM.';
COMMENT ON COLUMN feature.description IS 'Descripcion de la caracteristica. Ejemplo real: Memoria del equipo en GB.';

COMMENT ON TABLE item IS 'Item inventariable. Ejemplo real: Laptop Dell Latitude 7420.';
COMMENT ON COLUMN item.id IS 'Identificador de item. Ejemplo real: 1021.';
COMMENT ON COLUMN item.code IS 'Codigo unico visible del item. Ejemplo real: INV-LAP-00021.';
COMMENT ON COLUMN item.name IS 'Nombre del item. Ejemplo real: Laptop Dell Latitude 7420.';
COMMENT ON COLUMN item.description IS 'Descripcion del item. Ejemplo real: Equipo para laboratorio de software.';
COMMENT ON COLUMN item.cost IS 'Costo de adquisicion. Ejemplo real: 950.00.';
COMMENT ON COLUMN item.acquisition_date IS 'Fecha de compra. Ejemplo real: 2025-08-15.';
COMMENT ON COLUMN item.is_active IS 'Estado operativo del item. Ejemplo real: TRUE para item disponible.';
COMMENT ON COLUMN item.category_id IS 'FK a categoria. Ejemplo real: category_id=25 (Laptop).';
COMMENT ON COLUMN item.created_at IS 'Fecha de creacion del registro. Ejemplo real: 2026-01-10 14:00:00+00.';
COMMENT ON COLUMN item.updated_at IS 'Fecha de ultima actualizacion. Ejemplo real: 2026-03-10 08:00:00+00.';
COMMENT ON COLUMN item.deleted_at IS 'Fecha de baja logica. Ejemplo real: NULL cuando sigue activo.';

COMMENT ON TABLE item_feature IS 'Valores de caracteristicas por item. Ejemplo real: Laptop 1021 tiene RAM=16GB.';
COMMENT ON COLUMN item_feature.id IS 'Identificador de asignacion item-caracteristica. Ejemplo real: 5008.';
COMMENT ON COLUMN item_feature.value IS 'Valor de la caracteristica. Ejemplo real: 16GB o Negro.';
COMMENT ON COLUMN item_feature.feature_id IS 'FK a caracteristica. Ejemplo real: feature_id=3 (RAM).';
COMMENT ON COLUMN item_feature.item_id IS 'FK a item. Ejemplo real: item_id=1021.';

COMMENT ON TABLE location_type IS 'Catalogo de tipos de ubicacion. Ejemplo real: CAMPUS, BUILDING, ROOM, SHELF.';
COMMENT ON COLUMN location_type.id IS 'Identificador del tipo de ubicacion. Ejemplo real: 1.';
COMMENT ON COLUMN location_type.name IS 'Nombre del tipo de ubicacion. Ejemplo real: ROOM.';
COMMENT ON COLUMN location_type.description IS 'Descripcion del tipo. Ejemplo real: Espacio fisico para almacenar items.';

COMMENT ON TABLE location IS 'Ubicaciones fisicas jerarquicas. Ejemplo real: Campus Central > Biblioteca > Sala A > Estante 3.';
COMMENT ON COLUMN location.id IS 'Identificador de ubicacion. Ejemplo real: 77.';
COMMENT ON COLUMN location.name IS 'Nombre de la ubicacion. Ejemplo real: Estante 3.';
COMMENT ON COLUMN location.description IS 'Detalle de ubicacion. Ejemplo real: Estante metalico zona norte.';
COMMENT ON COLUMN location.parent_id IS 'Ubicacion padre. Ejemplo real: parent_id=45 (Sala A).';
COMMENT ON COLUMN location.type_id IS 'FK al tipo de ubicacion. Ejemplo real: type_id=4 (SHELF).';

COMMENT ON TABLE inventory IS 'Stock por item y ubicacion. Ejemplo real: 8 unidades de Calculadora FX-991 en Bodega 1.';
COMMENT ON COLUMN inventory.id IS 'Identificador de stock. Ejemplo real: 9001.';
COMMENT ON COLUMN inventory.amount IS 'Cantidad disponible. Ejemplo real: 8.';
COMMENT ON COLUMN inventory.location_id IS 'FK a ubicacion del stock. Ejemplo real: location_id=12 (Bodega 1).';
COMMENT ON COLUMN inventory.item_id IS 'FK a item almacenado. Ejemplo real: item_id=1300.';
COMMENT ON COLUMN inventory.updated_at IS 'Fecha de ultima actualizacion de stock. Ejemplo real: 2026-03-21 16:22:00+00.';

COMMENT ON TABLE period_type IS 'Catalogo de tipos de periodo. Ejemplo real: SEMESTER, TRIMESTER, ANNUAL.';
COMMENT ON COLUMN period_type.id IS 'Identificador del tipo de periodo. Ejemplo real: 1.';
COMMENT ON COLUMN period_type.name IS 'Nombre del tipo de periodo. Ejemplos de tipo/estado: ACTIVE, INACTIVE, PLANNED; tambien SEMESTER, TRIMESTER, ANNUAL segun negocio.';
COMMENT ON COLUMN period_type.description IS 'Descripcion del tipo. Ejemplo real: Periodo academico semestral.';
COMMENT ON COLUMN period_type.is_active IS 'Vigencia del tipo de periodo. Ejemplo real: TRUE para tipos en uso.';

COMMENT ON TABLE period IS 'Periodos operativos o academicos. Ejemplo real: 2026-1.';
COMMENT ON COLUMN period.id IS 'Identificador del periodo. Ejemplo real: 20261.';
COMMENT ON COLUMN period.name IS 'Nombre del periodo. Ejemplo real: 2026-1.';
COMMENT ON COLUMN period.description IS 'Detalle del periodo. Ejemplo real: Primer semestre 2026.';
COMMENT ON COLUMN period.start_date IS 'Fecha de inicio. Ejemplo real: 2026-01-15.';
COMMENT ON COLUMN period.end_date IS 'Fecha de fin. Ejemplo real: 2026-06-30.';
COMMENT ON COLUMN period.type_id IS 'FK al tipo de periodo. Ejemplo real: type_id=1 (SEMESTER).';
COMMENT ON COLUMN period.is_active IS 'Estado del periodo. Ejemplo real: TRUE para el periodo vigente.';

COMMENT ON TABLE movement_type IS 'Catalogo de tipos de movimiento. Ejemplo real: loan, return, reserve.';
COMMENT ON COLUMN movement_type.id IS 'Identificador del tipo de movimiento. Ejemplo real: 2.';
COMMENT ON COLUMN movement_type.name IS 'Nombre del tipo de movimiento. Ejemplo real: loan, return, reserve.';
COMMENT ON COLUMN movement_type.description IS 'Descripcion del tipo. Ejemplo real: Prestamo de item.';

COMMENT ON TABLE person IS 'Datos personales de miembros de la institucion. Ejemplo real: docente o estudiante.';
COMMENT ON COLUMN person.id IS 'Identificador de persona. Ejemplo real: 501.';
COMMENT ON COLUMN person.document_id IS 'Documento institucional o cedula. Ejemplo real: 0102345678.';
COMMENT ON COLUMN person.first_name IS 'Nombres de la persona. Ejemplo real: Maria Elena.';
COMMENT ON COLUMN person.last_name IS 'Apellidos de la persona. Ejemplo real: Perez Gomez.';
COMMENT ON COLUMN person.phone IS 'Telefono de contacto. Ejemplo real: +593 99 123 4567.';
COMMENT ON COLUMN person.degree IS 'Titulo academico o profesion. Ejemplo real: Ingeniera en Sistemas.';
COMMENT ON COLUMN person.address IS 'Direccion referencial. Ejemplo real: Av. Universitaria y Calle 10.';
COMMENT ON COLUMN person.birth_date IS 'Fecha de nacimiento. Ejemplo real: 1998-04-03.';
COMMENT ON COLUMN person.created_at IS 'Fecha de creacion de persona. Ejemplo real: 2026-01-02 12:00:00+00.';
COMMENT ON COLUMN person.updated_at IS 'Fecha de actualizacion de persona. Ejemplo real: 2026-02-11 18:30:00+00.';
COMMENT ON COLUMN person.deleted_at IS 'Fecha de baja logica de persona. Ejemplo real: NULL si continua activa.';

COMMENT ON TABLE person_group IS 'Relacion de agrupacion de personas. Ejemplo real: persona asignada al grupo de biblioteca.';
COMMENT ON COLUMN person_group.id IS 'Identificador de la asignacion. Ejemplo real: 300.';
COMMENT ON COLUMN person_group.person_id IS 'FK a persona asignada. Ejemplo real: person_id=501.';

COMMENT ON TABLE "user" IS 'Cuenta de acceso al sistema. Ejemplo real: usuario operador de biblioteca.';
COMMENT ON COLUMN "user".id IS 'Identificador de usuario. Ejemplo real: 45.';
COMMENT ON COLUMN "user".name IS 'Nombre de usuario visible. Ejemplo real: mlopez.';
COMMENT ON COLUMN "user".email IS 'Correo del usuario. Ejemplo real: mlopez@universidad.edu.';
COMMENT ON COLUMN "user".password_hash IS 'Hash de contrasena. Ejemplo real: valor bcrypt/argon2.';
COMMENT ON COLUMN "user".is_solvency IS 'Indicador de solvencia para prestamos. Ejemplo real: FALSE si tiene multas pendientes.';
COMMENT ON COLUMN "user".is_active IS 'Estado de la cuenta. Ejemplo real: TRUE cuando puede iniciar sesion.';
COMMENT ON COLUMN "user".person_id IS 'FK a persona vinculada. Ejemplo real: person_id=501.';
COMMENT ON COLUMN "user".created_at IS 'Fecha de creacion de usuario. Ejemplo real: 2026-01-05 09:00:00+00.';
COMMENT ON COLUMN "user".updated_at IS 'Fecha de ultima actualizacion de usuario. Ejemplo real: 2026-03-01 11:00:00+00.';
COMMENT ON COLUMN "user".deleted_at IS 'Fecha de baja logica de usuario. Ejemplo real: NULL para usuarios activos.';

COMMENT ON TABLE movement IS 'Cabecera de movimientos de inventario. Ejemplo real: prestamo 000345 al usuario 45.';
COMMENT ON COLUMN movement.id IS 'Identificador del movimiento. Ejemplo real: 345.';
COMMENT ON COLUMN movement.booking_date IS 'Fecha/hora de registro del movimiento. Ejemplo real: 2026-03-20 10:15:00+00.';
COMMENT ON COLUMN movement.estimated_return_date IS 'Fecha estimada de devolucion. Ejemplo real: 2026-03-27 18:00:00+00.';
COMMENT ON COLUMN movement.actual_return_date IS 'Fecha real de devolucion. Ejemplo real: 2026-03-28 09:30:00+00.';
COMMENT ON COLUMN movement.observations IS 'Notas del movimiento. Ejemplo real: Prestamo para practica de laboratorio.';
COMMENT ON COLUMN movement.user_id IS 'FK al usuario que realiza el movimiento. Ejemplo real: user_id=45.';
COMMENT ON COLUMN movement.type_id IS 'FK al tipo de movimiento. Ejemplo real: type_id=1 (loan).';
COMMENT ON COLUMN movement.period_id IS 'FK al periodo vigente del movimiento. Ejemplo real: period_id=20261.';
COMMENT ON COLUMN movement.created_at IS 'Fecha de creacion del movimiento. Ejemplo real: 2026-03-20 10:15:05+00.';
COMMENT ON COLUMN movement.updated_at IS 'Fecha de actualizacion del movimiento. Ejemplo real: 2026-03-28 09:30:10+00.';

COMMENT ON TABLE movement_detail IS 'Detalle de items involucrados en un movimiento. Ejemplo real: 2 calculadoras prestadas en el movimiento 345.';
COMMENT ON COLUMN movement_detail.id IS 'Identificador de detalle. Ejemplo real: 90012.';
COMMENT ON COLUMN movement_detail.movement_date IS 'Fecha/hora del detalle. Ejemplo real: 2026-03-20 10:15:30+00.';
COMMENT ON COLUMN movement_detail.amount IS 'Cantidad de unidades. Ejemplo real: 2.';
COMMENT ON COLUMN movement_detail.fine IS 'Multa asociada al detalle. Ejemplo real: 1.50 por retraso.';
COMMENT ON COLUMN movement_detail.observations IS 'Notas del detalle. Ejemplo real: Una unidad con rayones leves.';
COMMENT ON COLUMN movement_detail.inventory_id IS 'FK al registro de inventario. Ejemplo real: inventory_id=9001.';
COMMENT ON COLUMN movement_detail.movement_id IS 'FK a la cabecera de movimiento. Ejemplo real: movement_id=345.';

COMMENT ON TABLE return_status_type IS 'Catalogo de tipos de estado de devolucion. Ejemplo real: returned_ok, returned_late, damaged, lost.';
COMMENT ON COLUMN return_status_type.id IS 'Identificador del tipo de estado de devolucion. Ejemplo real: 1.';
COMMENT ON COLUMN return_status_type.name IS 'Nombre del tipo de estado. Ejemplo real: returned_late.';
COMMENT ON COLUMN return_status_type.description IS 'Descripcion del tipo de estado. Ejemplo real: Item devuelto fuera de plazo.';

COMMENT ON TABLE return_status IS 'Historial de estados de devolucion por detalle. Ejemplo real: detalle 90012 marcado como returned_late.';
COMMENT ON COLUMN return_status.id IS 'Identificador del estado de devolucion. Ejemplo real: 2200.';
COMMENT ON COLUMN return_status.type_id IS 'FK al tipo de estado de devolucion. Ejemplo real: type_id=2 (returned_late).';
COMMENT ON COLUMN return_status.status_date IS 'Fecha/hora del estado. Ejemplo real: 2026-03-28 09:35:00+00.';
COMMENT ON COLUMN return_status.observations IS 'Observaciones del estado. Ejemplo real: Retraso de 1 dia.';
COMMENT ON COLUMN return_status.movement_detail_id IS 'FK al detalle de movimiento. Ejemplo real: movement_detail_id=90012.';
COMMENT ON COLUMN return_status.created_at IS 'Fecha de creacion del estado. Ejemplo real: 2026-03-28 09:35:00+00.';
COMMENT ON COLUMN return_status.updated_at IS 'Fecha de actualizacion del estado. Ejemplo real: 2026-03-28 09:36:00+00.';

COMMENT ON TABLE audit_type IS 'Catalogo de tipos de auditoria. Ejemplo real: security, business, system.';
COMMENT ON COLUMN audit_type.id IS 'Identificador del tipo de auditoria. Ejemplo real: 1.';
COMMENT ON COLUMN audit_type.name IS 'Nombre del tipo de auditoria. Ejemplo real: security.';
COMMENT ON COLUMN audit_type.description IS 'Descripcion del tipo de auditoria. Ejemplo real: Eventos de seguridad y acceso.';
COMMENT ON COLUMN audit_type.created_at IS 'Fecha de creacion del tipo de auditoria. Ejemplo real: 2026-01-01 00:00:00+00.';

COMMENT ON TABLE audit IS 'Bitacora de eventos auditables del sistema. Ejemplo real: LOGIN_FAILED en modulo de autenticacion.';
COMMENT ON COLUMN audit.id IS 'Identificador del evento de auditoria. Ejemplo real: 80001.';
COMMENT ON COLUMN audit.entity_name IS 'Entidad afectada. Ejemplo real: user.';
COMMENT ON COLUMN audit.method IS 'Operacion realizada. Ejemplo real: INSERT, UPDATE, LOGIN_FAILED.';
COMMENT ON COLUMN audit.event_at IS 'Fecha/hora del evento. Ejemplo real: 2026-03-21 14:10:00+00.';
COMMENT ON COLUMN audit.details IS 'Detalle del evento. Ejemplo real: Intento fallido por contrasena incorrecta.';
COMMENT ON COLUMN audit.user_id IS 'FK al usuario asociado al evento. Ejemplo real: user_id=45.';
COMMENT ON COLUMN audit.type_id IS 'FK al tipo de auditoria. Ejemplo real: type_id=1 (security).';

COMMENT ON TABLE notification_type IS 'Catalogo de tipos de notificacion. Ejemplo real: info, warning, critical.';
COMMENT ON COLUMN notification_type.id IS 'Identificador del tipo de notificacion. Ejemplo real: 3.';
COMMENT ON COLUMN notification_type.name IS 'Nombre del tipo de notificacion. Ejemplo real: warning.';
COMMENT ON COLUMN notification_type.description IS 'Descripcion del tipo de notificacion. Ejemplo real: Notificacion de advertencia.';

COMMENT ON TABLE notification IS 'Notificaciones enviadas a usuarios. Ejemplo real: aviso de devolucion proxima.';
COMMENT ON COLUMN notification.id IS 'Identificador de notificacion. Ejemplo real: 7005.';
COMMENT ON COLUMN notification.title IS 'Titulo de la notificacion. Ejemplo real: Prestamo por vencer.';
COMMENT ON COLUMN notification.message IS 'Contenido de la notificacion. Ejemplo real: Tu prestamo vence en 24 horas.';
COMMENT ON COLUMN notification.sent_at IS 'Fecha/hora de envio. Ejemplo real: 2026-03-21 07:00:00+00.';
COMMENT ON COLUMN notification.is_read IS 'Marca de lectura. Ejemplo real: FALSE cuando el usuario aun no la abre.';
COMMENT ON COLUMN notification.user_id IS 'FK al usuario receptor. Ejemplo real: user_id=45.';
COMMENT ON COLUMN notification.type_id IS 'FK al tipo de notificacion. Ejemplo real: type_id=2 (warning).';

COMMENT ON TABLE profile IS 'Perfiles de acceso. Ejemplo real: admin, operator, viewer.';
COMMENT ON COLUMN profile.id IS 'Identificador de perfil. Ejemplo real: 1.';
COMMENT ON COLUMN profile.name IS 'Nombre de perfil. Ejemplo real: operator.';
COMMENT ON COLUMN profile.description IS 'Descripcion del perfil. Ejemplo real: Operador funcional.';
COMMENT ON COLUMN profile.is_active IS 'Estado del perfil. Ejemplo real: TRUE para perfiles habilitados.';

COMMENT ON TABLE user_profile IS 'Asignacion de perfiles a usuarios. Ejemplo real: usuario 45 con perfil operator.';
COMMENT ON COLUMN user_profile.id IS 'Identificador de asignacion usuario-perfil. Ejemplo real: 120.';
COMMENT ON COLUMN user_profile.user_id IS 'FK a usuario. Ejemplo real: user_id=45.';
COMMENT ON COLUMN user_profile.profile_id IS 'FK a perfil. Ejemplo real: profile_id=2 (operator).';

COMMENT ON TABLE "option" IS 'Opciones funcionales del sistema. Ejemplo real: MENU_PRESTAMOS_LISTAR.';
COMMENT ON COLUMN "option".id IS 'Identificador de opcion. Ejemplo real: 80.';
COMMENT ON COLUMN "option".name IS 'Nombre tecnico de opcion. Ejemplo real: MENU_PRESTAMOS_LISTAR.';
COMMENT ON COLUMN "option".description IS 'Descripcion funcional. Ejemplo real: Permite listar prestamos.';

COMMENT ON TABLE option_profile IS 'Permisos de opcion por perfil. Ejemplo real: profile operator puede usar MENU_PRESTAMOS_LISTAR.';
COMMENT ON COLUMN option_profile.id IS 'Identificador de asignacion opcion-perfil. Ejemplo real: 999.';
COMMENT ON COLUMN option_profile.profile_id IS 'FK a perfil autorizado. Ejemplo real: profile_id=2.';
COMMENT ON COLUMN option_profile.option_id IS 'FK a opcion autorizada. Ejemplo real: option_id=80.';

COMMENT ON TABLE subsystem IS 'Subsistemas funcionales. Ejemplo real: INVENTORY, SECURITY, REPORTS.';
COMMENT ON COLUMN subsystem.id IS 'Identificador de subsistema. Ejemplo real: 10.';
COMMENT ON COLUMN subsystem.name IS 'Nombre del subsistema. Ejemplo real: INVENTORY.';
COMMENT ON COLUMN subsystem.description IS 'Descripcion del subsistema. Ejemplo real: Gestion de inventario institucional.';

COMMENT ON TABLE menu IS 'Menus de navegacion por subsistema. Ejemplo real: Prestamos dentro de INVENTORY.';
COMMENT ON COLUMN menu.id IS 'Identificador de menu. Ejemplo real: 33.';
COMMENT ON COLUMN menu.name IS 'Nombre de menu. Ejemplo real: Prestamos.';
COMMENT ON COLUMN menu.description IS 'Descripcion de menu. Ejemplo real: Opciones de registro y devolucion.';
COMMENT ON COLUMN menu.subsystem_id IS 'FK al subsistema del menu. Ejemplo real: subsystem_id=10 (INVENTORY).';

COMMENT ON TABLE option_menu IS 'Relacion entre opciones y menus. Ejemplo real: opcion MENU_PRESTAMOS_LISTAR pertenece al menu Prestamos.';
COMMENT ON COLUMN option_menu.id IS 'Identificador de relacion opcion-menu. Ejemplo real: 1500.';
COMMENT ON COLUMN option_menu.option_id IS 'FK a opcion del menu. Ejemplo real: option_id=80.';
COMMENT ON COLUMN option_menu.menu_id IS 'FK a menu asociado. Ejemplo real: menu_id=33.';

COMMENT ON TABLE "class" IS 'Clases de dominio o modulos logicos. Ejemplo real: movement_controller.';
COMMENT ON COLUMN "class".id IS 'Identificador de clase. Ejemplo real: 14.';
COMMENT ON COLUMN "class".name IS 'Nombre de clase. Ejemplo real: movement_controller.';
COMMENT ON COLUMN "class".description IS 'Descripcion de clase. Ejemplo real: Gestiona prestamos y devoluciones.';

COMMENT ON TABLE subsystem_class IS 'Relacion entre subsistemas y clases. Ejemplo real: INVENTORY incluye movement_controller.';
COMMENT ON COLUMN subsystem_class.id IS 'Identificador de relacion subsistema-clase. Ejemplo real: 700.';
COMMENT ON COLUMN subsystem_class.subsystem_id IS 'FK a subsistema. Ejemplo real: subsystem_id=10.';
COMMENT ON COLUMN subsystem_class.class_id IS 'FK a clase. Ejemplo real: class_id=14.';

COMMENT ON TABLE "method" IS 'Metodos funcionales autorizables. Ejemplo real: createMovement, returnItem, listInventory.';
COMMENT ON COLUMN "method".id IS 'Identificador de metodo. Ejemplo real: 200.';
COMMENT ON COLUMN "method".name IS 'Nombre del metodo. Ejemplo real: createMovement.';
COMMENT ON COLUMN "method".description IS 'Descripcion del metodo. Ejemplo real: Crea un nuevo prestamo de item.';

COMMENT ON TABLE class_method IS 'Relacion entre clase y metodo. Ejemplo real: movement_controller -> createMovement.';
COMMENT ON COLUMN class_method.id IS 'Identificador de relacion clase-metodo. Ejemplo real: 810.';
COMMENT ON COLUMN class_method.class_id IS 'FK a clase. Ejemplo real: class_id=14.';
COMMENT ON COLUMN class_method.method_id IS 'FK a metodo. Ejemplo real: method_id=200.';

COMMENT ON TABLE method_profile IS 'Autorizacion de metodo por perfil. Ejemplo real: operator puede ejecutar createMovement.';
COMMENT ON COLUMN method_profile.id IS 'Identificador de autorizacion metodo-perfil. Ejemplo real: 930.';
COMMENT ON COLUMN method_profile.method_id IS 'FK a metodo autorizado. Ejemplo real: method_id=200.';
COMMENT ON COLUMN method_profile.profile_id IS 'FK a perfil autorizado. Ejemplo real: profile_id=2.';

COMMENT ON TABLE "transaction" IS 'Mapa de transaccion funcional por subsistema, clase y metodo. Ejemplo real: INVENTORY + movement_controller + createMovement.';
COMMENT ON COLUMN "transaction".id IS 'Identificador de transaccion. Ejemplo real: 4001.';
COMMENT ON COLUMN "transaction".subsystem_id IS 'FK a subsistema de la transaccion. Ejemplo real: subsystem_id=10.';
COMMENT ON COLUMN "transaction".class_id IS 'FK a clase de la transaccion. Ejemplo real: class_id=14.';
COMMENT ON COLUMN "transaction".method_id IS 'FK a metodo de la transaccion. Ejemplo real: method_id=200.';

COMMIT;

-- ============================================================
-- V2__Audit_Indexes.sql
-- Objetivo: Indices de rendimiento, funcionales y trazabilidad.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Indices FK (rendimiento joins)
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_category_type_id ON category(type_id);
CREATE INDEX IF NOT EXISTS ix_item_category_id ON item(category_id);
CREATE INDEX IF NOT EXISTS ix_item_feature_feature_id ON item_feature(feature_id);
CREATE INDEX IF NOT EXISTS ix_item_feature_item_id ON item_feature(item_id);
CREATE INDEX IF NOT EXISTS ix_location_parent_id ON location(parent_id);
CREATE INDEX IF NOT EXISTS ix_location_type_id ON location(type_id);
CREATE INDEX IF NOT EXISTS ix_inventory_location_id ON inventory(location_id);
CREATE INDEX IF NOT EXISTS ix_inventory_item_id ON inventory(item_id);
CREATE INDEX IF NOT EXISTS ix_period_type_id ON period(type_id);
CREATE INDEX IF NOT EXISTS ix_person_group_person_id ON person_group(person_id);
CREATE INDEX IF NOT EXISTS ix_user_person_id ON "user"(person_id);
CREATE INDEX IF NOT EXISTS ix_movement_user_id ON movement(user_id);
CREATE INDEX IF NOT EXISTS ix_movement_type_id ON movement(type_id);
CREATE INDEX IF NOT EXISTS ix_movement_period_id ON movement(period_id);
CREATE INDEX IF NOT EXISTS ix_movement_detail_inventory_id ON movement_detail(inventory_id);
CREATE INDEX IF NOT EXISTS ix_movement_detail_movement_id ON movement_detail(movement_id);
CREATE INDEX IF NOT EXISTS ix_return_status_type_id ON return_status(type_id);
CREATE INDEX IF NOT EXISTS ix_return_status_movement_detail_id ON return_status(movement_detail_id);
CREATE INDEX IF NOT EXISTS ix_audit_user_id ON audit(user_id);
CREATE INDEX IF NOT EXISTS ix_audit_type_id ON audit(type_id);
CREATE INDEX IF NOT EXISTS ix_notification_user_id ON notification(user_id);
CREATE INDEX IF NOT EXISTS ix_notification_type_id ON notification(type_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_user_id ON user_profile(user_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_profile_id ON user_profile(profile_id);
CREATE INDEX IF NOT EXISTS ix_option_profile_profile_id ON option_profile(profile_id);
CREATE INDEX IF NOT EXISTS ix_option_profile_option_id ON option_profile(option_id);
CREATE INDEX IF NOT EXISTS ix_menu_subsystem_id ON menu(subsystem_id);
CREATE INDEX IF NOT EXISTS ix_option_menu_option_id ON option_menu(option_id);
CREATE INDEX IF NOT EXISTS ix_option_menu_menu_id ON option_menu(menu_id);
CREATE INDEX IF NOT EXISTS ix_subsystem_class_subsystem_id ON subsystem_class(subsystem_id);
CREATE INDEX IF NOT EXISTS ix_subsystem_class_class_id ON subsystem_class(class_id);
CREATE INDEX IF NOT EXISTS ix_class_method_class_id ON class_method(class_id);
CREATE INDEX IF NOT EXISTS ix_class_method_method_id ON class_method(method_id);
CREATE INDEX IF NOT EXISTS ix_method_profile_method_id ON method_profile(method_id);
CREATE INDEX IF NOT EXISTS ix_method_profile_profile_id ON method_profile(profile_id);
 CREATE INDEX IF NOT EXISTS ix_transaction_subsystem_id ON "transaction"(subsystem_id);
CREATE INDEX IF NOT EXISTS ix_transaction_class_id ON "transaction"(class_id);
CREATE INDEX IF NOT EXISTS ix_transaction_method_id ON "transaction"(method_id);

-- ------------------------------------------------------------
-- Indices funcionales sobre fecha (created_at::DATE)
-- Para tablas transaccionales principales.
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_movement_created_date ON movement ((created_at::DATE));

-- ------------------------------------------------------------
-- Soft delete + unicidad funcional (case-insensitive)
-- ------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS uq_item_code_active
    ON item (code)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_person_document_id_lower_active
    ON person (LOWER(document_id))
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email_lower_active
    ON "user" (LOWER(email))
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_name_lower_active
    ON "user" (LOWER(name))
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_profile_name_lower_active
    ON profile (LOWER(name));

-- ------------------------------------------------------------
-- Trigger generico para mantener updated_at automaticamente
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    t TEXT;
    tables TEXT[] := ARRAY[
        'category_type', 'item', 'inventory', 'person', 'user',
        'movement', 'return_status', 'transaction'
    ];
BEGIN
    FOREACH t IN ARRAY tables
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I', t, t);
        EXECUTE format(
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            t,
            t
        );
    END LOOP;
END;
$$;

COMMIT;

-- ============================================================
-- V3__Insert_Base_Catalogs.sql
-- Objetivo: Seeds minimos de catalogos base y perfiles.
-- ============================================================

BEGIN;

INSERT INTO movement_type (name, description)
VALUES
    ('loan', 'Prestamo de item'),
    ('return', 'Devolucion de item'),
    ('reserve', 'Reserva de item')
ON CONFLICT (name) DO NOTHING;

INSERT INTO period_type (name, description)
VALUES
    ('semester', 'Periodo semestral'),
    ('trimester', 'Periodo trimestral'),
    ('annual', 'Periodo anual')
ON CONFLICT (name) DO NOTHING;

INSERT INTO audit_type (name, description)
VALUES
    ('security', 'Eventos de seguridad y acceso'),
    ('business', 'Eventos funcionales de negocio'),
    ('system', 'Eventos tecnicos del sistema')
ON CONFLICT (name) DO NOTHING;

INSERT INTO notification_type (name, description)
VALUES
    ('info', 'Notificacion informativa'),
    ('warning', 'Notificacion de advertencia'),
    ('critical', 'Notificacion critica')
ON CONFLICT (name) DO NOTHING;

INSERT INTO return_status_type (name, description)
VALUES
    ('returned_ok', 'Item devuelto sin novedades'),
    ('returned_late', 'Item devuelto fuera de plazo'),
    ('damaged', 'Item devuelto con dano'),
    ('lost', 'Item marcado como perdido')
ON CONFLICT (name) DO NOTHING;

INSERT INTO profile (name, description, is_active)
VALUES
    ('admin', 'Administrador del sistema', TRUE),
    ('operator', 'Operador funcional', TRUE),
    ('viewer', 'Consulta y reportes', TRUE)
ON CONFLICT DO NOTHING;

COMMIT;
